version: '{build}'

image: Visual Studio 2019

init:
  # use a minimal path
  - set PATH=C:\ruby%ruby_version%\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32
  # Load ruby trunk build
  - if %ruby_version%==_trunk (
      appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:\ruby_trunk.7z &
      7z x C:\ruby_trunk.7z -oC:\ruby_trunk
    )

platform: x64

install:
  - ruby --version
  - gem --version
  # Assume we can use the version of bundler that Appveyor has packaged with each ruby version
  - bundle install

build: off

test_script:
  - rake gem:binary
  - rake -rdevkit test:all

environment:
  matrix:
    - ruby_version: _trunk
    - ruby_version: 30-x64
    - ruby_version: 30
    - ruby_version: 27-x64
    - ruby_version: 27
    - ruby_version: 26-x64
    - ruby_version: 26
    - ruby_version: 25-x64
    - ruby_version: 25
    - ruby_version: 24-x64
    - ruby_version: 24
    - ruby_version: 23-x64
    - ruby_version: 23

matrix:
  allow_failures:
    - ruby_version: _trunk
